steps:
    - label: ":docker: Build and push server image"
      command: .buildkite/build.sh

    - wait

    - label: ":terraform: Deploy Terrarium"
      if: 'build.branch == "main"'
      command: .buildkite/deploy.sh
