name: Build

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - .github/workflows/build.yml
            - image/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                  echo "${GITHUB_TOKEN}" | docker login ghcr.io --username "${GITHUB_REPOSITORY%%/*}" --password-stdin
                  docker pull "ghcr.io/${GITHUB_REPOSITORY}:main"
                  docker build --tag "ghcr.io/${GITHUB_REPOSITORY}:main" image
                  docker push "ghcr.io/${GITHUB_REPOSITORY}:main"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
