name: Build and publish server image

on:
    workflow_dispatch:
    push:
        paths:
            - .github/workflows/build.yml
            - image/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                  echo "${GITHUB_TOKEN}" | docker login ghcr.io --username "${GITHUB_REPOSITORY%%/*}" --password-stdin
                  docker build --tag terrarium image
                  docker run terrarium aws --version
                  docker run terrarium tailscale --version
                  docker tag terrarium "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}"
                  docker push "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
